base_url = "https://not-matthias.github.io/apollo/"
title = "dhruv-ahuja"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true

theme = "apollo-custom"

[extra]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
    { name = "github", url = "https://github.com/not-matthias/", icon = "github" },
]

theme = "toggle"

custom_css = []

[extra.analytics]
enabled = true
goatcounter_user = "your_user"
goatcounter_host = "example.com" # default= goatcounter.com
