base_url = "https://dhruv-ahuja.github.io"
title = "dhruv-ahuja"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true

theme = "apollo-custom"

[markdown]
highlight_code = true
highlight_theme = "material-dark"

[extra]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 }
]

socials = [
    { name = "email", url = "mailto:dhruvahuja2k@gmail.com", icon = "email" },
    { name = "linkedin", url = "https://www.linkedin.com/in/dhruvahuja2k/", icon = "linkedin" },
    { name = "github", url = "https://github.com/dhruv-ahuja/", icon = "github" },
]

theme = "toggle"

custom_css = []

[extra.analytics]
enabled = true
goatcounter_user = "dhruv-ahuja"
